"""Lie bracket computation for thermostat vector fields.

For 1D harmonic oscillator + thermostat, the vector field is:
    F = (p, -q - g(xi)*p, (p^2 - 1)/Q)

We split into Hamiltonian and friction parts:
    X = (p, -q, 0)           [Hamiltonian flow]
    Y = (0, -g(xi)*p, (p^2-1)/Q)  [friction + thermostat drive]

The Lie bracket is [X,Y](x) = DY(x)*X(x) - DX(x)*Y(x)
where DX, DY are Jacobian matrices.

We compute iterated brackets up to depth 4 and evaluate rank of the full
Lie algebra generated by {X, Y} at each point.

The Hoermander-like condition (full rank = 3 at generic points) is necessary
for accessibility/controllability. For deterministic ODEs, this is necessary
but NOT sufficient for ergodicity -- but rank deficiency DOES imply the
existence of invariant manifolds (i.e., obstructions to ergodicity).

References:
- Hoermander (1967), Hypoelliptic second order differential equations
- Jurdjevic (1997), Geometric Control Theory
- Butler (2018), Nose-Hoover equations with a temperature-dependent thermostat
- Butler (2021), KAM tori and Nose thermostat
"""

import sympy as sp
from sympy import Matrix, Function, symbols, diff, simplify, expand
from sympy import log, cosh, atan, sqrt, Rational, factor
from itertools import combinations
import json


def jacobian(V, state):
    """Compute Jacobian matrix of vector field V w.r.t. state."""
    n = len(state)
    J = sp.zeros(n, n)
    for i in range(n):
        for j in range(n):
            J[i, j] = diff(V[i], state[j])
    return J


def lie_bracket(V1, V2, state):
    """Compute Lie bracket [V1, V2] = DV2 * V1 - DV1 * V2."""
    DV1 = jacobian(V1, state)
    DV2 = jacobian(V2, state)
    return simplify(DV2 * V1 - DV1 * V2)


def compute_brackets_for_g(g_expr, name, verbose=True):
    """Compute all Lie brackets for a specific friction function g(xi).

    The FULL vector field F generates a 1-dimensional distribution.
    We study the Lie algebra generated by the full field F with itself
    under the flow -- but since F is a single field, [F,F]=0.

    Instead, the relevant object is the ACCESSIBILITY algebra of the
    controlled system where X and Y are two independent "inputs".
    More precisely, we study whether the vector fields
    {F} together with all Lie brackets generate R^3.

    For a SINGLE autonomous ODE, the relevant question is:
    Does the orbit of F through a point fill a 3D region?

    The correct approach: compute brackets of the FULL field F with
    coordinate vector fields, or equivalently check the Jacobian
    structure. But the standard Hoermander analysis applies to
    SDEs (X_0 + sum X_i dW_i).

    For our deterministic system, the right object is:
    - The Lie algebra L(X, Y) generated by X and Y
    - If dim L(X,Y)(x) = 3 for generic x, the system is "controllable"
      in the sense that the X-Y splitting admits access to all directions
    - This is related to but distinct from ergodicity

    We compute L(X,Y) and determine its dimension at each point.
    """
    q, p, xi, Q = symbols('q p xi Q', real=True)
    state = Matrix([q, p, xi])

    X = Matrix([p, -q, 0])
    Y = Matrix([0, -g_expr * p, (p**2 - 1) / Q])
    F = X + Y  # Full vector field

    if verbose:
        print(f"\n{'='*60}")
        print(f"  {name}: g(xi) = {g_expr}")
        print(f"{'='*60}")
        print(f"  X = {X.T}")
        print(f"  Y = {Y.T}")

    # Compute brackets of X and Y
    brackets = {}
    brackets['X'] = X
    brackets['Y'] = Y

    # [X, Y]
    XY = lie_bracket(X, Y, state)
    brackets['[X,Y]'] = XY

    # [X, [X, Y]]
    XXY = lie_bracket(X, XY, state)
    brackets['[X,[X,Y]]'] = XXY

    # [Y, [X, Y]]
    YXY = lie_bracket(Y, XY, state)
    brackets['[Y,[X,Y]]'] = YXY

    # [X, [X, [X, Y]]]
    XXXY = lie_bracket(X, XXY, state)
    brackets['[X,[X,[X,Y]]]'] = XXXY

    # [Y, [X, [X, Y]]]
    YXXY = lie_bracket(Y, XXY, state)
    brackets['[Y,[X,[X,Y]]]'] = YXXY

    # [Y, [Y, [X, Y]]]
    YYXY = lie_bracket(Y, YXY, state)
    brackets['[Y,[Y,[X,Y]]]'] = YYXY

    # [X, [Y, [X, Y]]]
    XYXY = lie_bracket(X, YXY, state)
    brackets['[X,[Y,[X,Y]]]'] = XYXY

    if verbose:
        print(f"\nKey Lie brackets:")
        for bname in ['[X,Y]', '[X,[X,Y]]', '[Y,[X,Y]]', '[X,[X,[X,Y]]]',
                       '[Y,[X,[X,Y]]]', '[X,[Y,[X,Y]]]', '[Y,[Y,[X,Y]]]']:
            bvec = brackets[bname]
            print(f"  {bname} = {bvec.T}")

    # Now check: which triples from {X, Y, [X,Y], [X,[X,Y]], [Y,[X,Y]], ...}
    # span R^3?
    # The Lie algebra dimension at a point = rank of all bracket vectors.
    bracket_names = ['X', 'Y', '[X,Y]', '[X,[X,Y]]', '[Y,[X,Y]]',
                     '[X,[X,[X,Y]]]', '[Y,[X,[X,Y]]]', '[X,[Y,[X,Y]]]',
                     '[Y,[Y,[X,Y]]]']
    bracket_vecs = [brackets[n] for n in bracket_names]

    # Form the full bracket matrix (3 x N)
    full_matrix = Matrix([bracket_vecs]).T

    if verbose:
        print(f"\nFull bracket matrix ({full_matrix.rows}x{full_matrix.cols}):")

    # Compute symbolic determinants of all 3x3 submatrices
    # to find conditions for rank < 3
    n_brackets = len(bracket_vecs)
    nonzero_dets = []

    for combo in combinations(range(n_brackets), 3):
        names_c = [bracket_names[i] for i in combo]
        M = Matrix([[bracket_vecs[combo[0]][r], bracket_vecs[combo[1]][r],
                      bracket_vecs[combo[2]][r]] for r in range(3)])
        det_val = simplify(M.det())
        if det_val != 0:
            nonzero_dets.append((names_c, det_val))

    if verbose:
        print(f"\n  Non-zero determinants ({len(nonzero_dets)} found):")
        for names_c, det_val in nonzero_dets[:8]:
            det_short = det_val
            print(f"    {names_c}: det = {det_short}")
        if len(nonzero_dets) > 8:
            print(f"    ... and {len(nonzero_dets) - 8} more")

    # The zero set of ALL determinants = the set where rank < 3
    # If any determinant is non-vanishing (not identically zero on a
    # positive-measure set), rank = 3 generically.
    #
    # For NH: the zero set includes {xi=0}, which has measure zero.
    # KEY QUESTION: is there a positive-measure set where ALL dets vanish?

    # Check: what is the common zero set?
    # If we have det1 = f1(q,p,xi) and det2 = f2(q,p,xi), the common
    # zero set is {f1=0} ∩ {f2=0}, which generically has codimension 2.

    # For practical purposes, evaluate numerically at a grid
    import numpy as np

    Q_val = sp.Rational(1, 2)
    # Test points avoiding degenerate cases
    test_grid = []
    for qv in [-1.5, -0.5, 0.5, 1.5]:
        for pv in [-1.5, -0.5, 0.5, 1.5]:
            for xv in [-2.0, -0.5, 0.0, 0.5, 2.0]:
                test_grid.append((qv, pv, xv))

    rank_counts = {0: 0, 1: 0, 2: 0, 3: 0}
    rank2_points = []

    for qv, pv, xv in test_grid:
        subs = {q: qv, p: pv, xi: xv, Q: Q_val}
        cols_num = []
        for bvec in bracket_vecs:
            vec = [float(bvec[r].subs(subs).evalf()) for r in range(3)]
            cols_num.append(vec)
        M_num = np.array(cols_num).T
        rank = np.linalg.matrix_rank(M_num, tol=1e-8)
        rank_counts[rank] = rank_counts.get(rank, 0) + 1
        if rank < 3:
            rank2_points.append((qv, pv, xv, rank))

    if verbose:
        print(f"\n  Rank distribution over {len(test_grid)} test points (Q={Q_val}):")
        for r in [3, 2, 1, 0]:
            if rank_counts[r] > 0:
                print(f"    rank={r}: {rank_counts[r]} points ({100*rank_counts[r]/len(test_grid):.1f}%)")
        if rank2_points:
            print(f"  Rank-deficient points:")
            for pt in rank2_points[:10]:
                print(f"    (q={pt[0]}, p={pt[1]}, xi={pt[2]}): rank={pt[3]}")

    # Determine if generically full rank
    frac_full = rank_counts[3] / len(test_grid)
    generic_full = frac_full > 0.9

    # Find the zero set analytically
    # The rank < 3 set is determined by vanishing of ALL 3x3 minors
    # For xi=0 with g(0)=0: Y and all ad^k_X(Y) become proportional
    # because g(xi) factors out of the first two components.
    # The [Y,[X,Y]] bracket brings in g'(xi) which is nonzero at xi=0
    # for all our functions.

    # Check specifically at xi=0
    xi0_ranks = []
    for qv in [-1.0, 0.5, 1.0]:
        for pv in [-1.0, 0.5, 1.0]:
            subs = {q: qv, p: pv, xi: 0, Q: Q_val}
            cols_num = []
            for bvec in bracket_vecs:
                vec = [float(bvec[r].subs(subs).evalf()) for r in range(3)]
                cols_num.append(vec)
            M_num = np.array(cols_num).T
            rank = np.linalg.matrix_rank(M_num, tol=1e-8)
            xi0_ranks.append((qv, pv, rank))

    if verbose:
        print(f"\n  Rank at xi=0 (critical surface where g(0)=0):")
        for qv, pv, rank in xi0_ranks:
            print(f"    (q={qv}, p={pv}, xi=0): rank={rank}")

    return brackets, nonzero_dets, rank_counts, rank2_points, (q, p, xi, Q)


def analyze_zero_set():
    """Analyze the zero set of bracket determinants for each friction.

    The KEY theoretical result:

    For general g(xi), det(Y | [X,Y] | [X,[X,Y]]) = -2(p^2+q^2)*g(xi)^2/Q.
    This vanishes iff g(xi)=0 or (q,p)=(0,0).

    For NH: g(xi)=xi, so g(xi)=0 iff xi=0. The zero set is {xi=0} U {q=p=0}.
    For Log-Osc: g(xi)=2xi/(1+xi^2), so g(xi)=0 iff xi=0. Same zero set.
    For Tanh: g(xi)=tanh(xi), so g(xi)=0 iff xi=0. Same zero set.
    For Arctan: g(xi)=atan(xi), so g(xi)=0 iff xi=0. Same zero set.

    So ALL four frictions have the same zero set for the primary determinant!
    The difference must come from HIGHER brackets evaluated ON the zero set.

    At xi=0 (where the primary det vanishes), we need [Y,[X,Y]] or other
    brackets to recover full rank. The [Y,[X,Y]] bracket involves g'(xi),
    and since g'(0) != 0 for all four functions, this should give rank 3.

    The REAL distinction between NH and bounded frictions is NOT about
    the Lie bracket rank (which is generically 3 for ALL of them) but about:
    1. The MEASURE of the rank-deficient set
    2. The RATE at which rank degrades near the zero set
    3. The dynamical significance (does the trajectory spend time near {xi=0}?)
    """
    q, p, xi, Q = symbols('q p xi Q', real=True)
    g = Function('g')
    state = Matrix([q, p, xi])

    print("\n" + "="*60)
    print("ZERO SET ANALYSIS")
    print("="*60)

    # The primary determinant for general g
    print("\nFor general g(xi):")
    print("  det(Y | [X,Y] | ad^2_X(Y)) = -2*(p^2+q^2)*g(xi)^2/Q")
    print("  Zero set: {g(xi)=0} U {q=p=0}")
    print("  For ALL our frictions: g(0)=0, so {xi=0} is always in the zero set.")

    # Now check: at xi=0, does [Y,[X,Y]] restore rank?
    frictions = {
        'NH': xi,
        'Log-Osc': 2*xi/(1+xi**2),
        'Tanh': sp.tanh(xi),
        'Arctan': sp.atan(xi),
    }

    print("\nAt xi=0, the [Y,[X,Y]] bracket involves g'(0):")
    for name, g_expr in frictions.items():
        gp0 = diff(g_expr, xi).subs(xi, 0)
        gpp0 = diff(g_expr, xi, 2).subs(xi, 0)
        print(f"  {name}: g'(0) = {gp0}, g''(0) = {gpp0}")

    # The [Y,[X,Y]] bracket at xi=0:
    # For general g with g(0)=0, g'(0)=c:
    # Y|_{xi=0} = (0, 0, (p^2-1)/Q) since g(0)=0
    # [X,Y]|_{xi=0} = (0, 0, -2pq/Q) since g(0)=0
    # [Y,[X,Y]]|_{xi=0} involves g'(0) * p terms

    print("\nEvaluating [Y,[X,Y]] at xi=0 for each friction:")

    for name, g_expr in frictions.items():
        X = Matrix([p, -q, 0])
        Y_s = Matrix([0, -g_expr * p, (p**2 - 1) / Q])

        XY = lie_bracket(X, Y_s, state)
        YXY = lie_bracket(Y_s, XY, state)
        YXY_at_0 = simplify(YXY.subs(xi, 0))
        print(f"  {name}: [Y,[X,Y]]|_{{xi=0}} = {YXY_at_0.T}")

        # Also check [Y,[X,[X,Y]]]
        XXY = lie_bracket(X, XY, state)
        YXXY = lie_bracket(Y_s, XXY, state)
        YXXY_at_0 = simplify(YXXY.subs(xi, 0))
        print(f"         [Y,[X,[X,Y]]]|_{{xi=0}} = {YXXY_at_0.T}")

    # The KEY insight: at xi=0, Y = (0, 0, (p^2-1)/Q) is purely in the
    # xi-direction (when g(0)=0). Meanwhile [X,Y] at xi=0 is also purely
    # in xi-direction. So we need [Y,[X,Y]] to provide q,p components.
    #
    # [Y,[X,Y]] at xi=0 has nonzero q,p components involving g'(0).
    # Since g'(0)=1 for NH and g'(0)=2 for Log-Osc etc., ALL frictions
    # get rank 3 at generic points of {xi=0}.
    #
    # CONCLUSION: The Lie algebra has full rank (3) at generic points for
    # ALL four friction functions, including NH. The rank drops only on
    # lower-dimensional sets (measure zero).
    #
    # This means the Lie bracket / Hoermander condition does NOT distinguish
    # NH from bounded frictions! Both satisfy the bracket condition generically.
    #
    # The failure of NH ergodicity (KAM tori) is a DYNAMICAL phenomenon,
    # not a controllability/bracket phenomenon. Butler (2018, 2021) proves
    # KAM tori persist for NH despite the bracket condition being satisfied.

    print("\n" + "="*60)
    print("CONCLUSION")
    print("="*60)
    print("""
ALL four friction functions (NH, Log-Osc, Tanh, Arctan) produce
Lie algebras of FULL RANK (3) at generic points in (q,p,xi) space.

The rank-deficient set for all four is the same:
  {g(xi)=0} ∩ {specific (q,p) conditions}
which has measure zero in R^3.

This means the Hoermander/controllability bracket condition does NOT
distinguish NH from bounded-friction thermostats.

The non-ergodicity of NH (KAM tori) is a DYNAMICAL phenomenon:
- Butler (2018, 2021) proves KAM tori persist for ANY single thermostat
  at weak coupling, regardless of the friction function g(xi).
- The bracket condition (controllability) is NECESSARY but not SUFFICIENT
  for ergodicity of deterministic ODEs.
- The gap between controllability and ergodicity is fundamental:
  controllability says "there exist controls to reach any point" but
  the ACTUAL trajectory (with no control freedom) may be trapped on
  invariant manifolds.

The correct explanation for why bounded frictions improve ergodicity
is NOT "they satisfy the Hoermander condition while NH doesn't" but
rather "they DEFORM KAM tori more strongly," as shown by the Lyapunov
exponent analysis in unified-theory-007.
""")


def numerical_rank_grid(g_expr, name, Q_val=0.5, n_grid=40):
    """Compute bracket rank on a grid for visualization.

    Returns arrays for heatmap plotting.
    """
    import numpy as np

    q_sym, p_sym, xi_sym, Q_sym = symbols('q p xi Q', real=True)
    state = Matrix([q_sym, p_sym, xi_sym])

    X = Matrix([p_sym, -q_sym, 0])
    Y = Matrix([0, -g_expr * p_sym, (p_sym**2 - 1) / Q_sym])

    # Compute brackets symbolically once
    XY = lie_bracket(X, Y, state)
    XXY = lie_bracket(X, XY, state)
    YXY = lie_bracket(Y, XY, state)
    XXXY = lie_bracket(X, XXY, state)
    YXXY = lie_bracket(Y, XXY, state)
    XYXY = lie_bracket(X, YXY, state)

    all_brackets = [X, Y, XY, XXY, YXY, XXXY, YXXY, XYXY]

    # Lambdify for speed
    from sympy import lambdify
    bracket_funcs = []
    for bvec in all_brackets:
        f = lambdify((q_sym, p_sym, xi_sym, Q_sym),
                     [bvec[0], bvec[1], bvec[2]], 'numpy')
        bracket_funcs.append(f)

    # Grid: fix xi at several slices, scan (q, p)
    q_vals = np.linspace(-3, 3, n_grid)
    p_vals = np.linspace(-3, 3, n_grid)
    xi_slices = [-2.0, -0.5, 0.0, 0.5, 2.0]

    results = {}
    for xi_val in xi_slices:
        rank_grid = np.zeros((n_grid, n_grid), dtype=int)
        for i, qv in enumerate(q_vals):
            for j, pv in enumerate(p_vals):
                cols = []
                for bf in bracket_funcs:
                    try:
                        vec = bf(qv, pv, xi_val, Q_val)
                        cols.append(vec)
                    except Exception:
                        cols.append([0, 0, 0])
                M = np.array(cols).T  # 3 x N
                rank = np.linalg.matrix_rank(M, tol=1e-8)
                rank_grid[j, i] = rank  # j=p index, i=q index
        results[xi_val] = rank_grid

    return q_vals, p_vals, xi_slices, results


def save_results(all_results):
    """Save numerical results to file."""
    import numpy as np

    output_lines = []
    output_lines.append("# Lie Bracket Rank Analysis Results")
    output_lines.append("# Q = 0.5, grid = 40x40, xi slices = [-2, -0.5, 0, 0.5, 2]")
    output_lines.append("")

    for name, (q_vals, p_vals, xi_slices, grids) in all_results.items():
        output_lines.append(f"\n## {name}")
        for xi_val in xi_slices:
            grid = grids[xi_val]
            n_total = grid.size
            n_full = np.sum(grid == 3)
            n_rank2 = np.sum(grid == 2)
            n_rank1 = np.sum(grid <= 1)
            output_lines.append(f"  xi={xi_val:+.1f}: rank3={n_full}/{n_total} "
                                f"({100*n_full/n_total:.1f}%), "
                                f"rank2={n_rank2}, rank<=1={n_rank1}")

    path = "/Users/wujiewang/code/det-sampler/.worktrees/hormander-ergo-017/orbits/hormander-ergo-017/bracket_rank_results.txt"
    with open(path, 'w') as f:
        f.write('\n'.join(output_lines))
    print(f"\nResults saved to {path}")


if __name__ == '__main__':
    print("Lie Bracket Analysis for Thermostat Ergodicity")
    print("=" * 60)

    xi_sym = symbols('xi', real=True)
    frictions = {
        'NH': xi_sym,
        'Log-Osc': 2*xi_sym/(1+xi_sym**2),
        'Tanh': sp.tanh(xi_sym),
        'Arctan': sp.atan(xi_sym),
    }

    # 1. Symbolic bracket computation for each friction
    all_bracket_data = {}
    for name, g_expr in frictions.items():
        data = compute_brackets_for_g(g_expr, name)
        all_bracket_data[name] = data

    # 2. Zero set analysis (the key theoretical result)
    analyze_zero_set()

    # 3. Numerical rank grids for visualization
    print("\n" + "="*60)
    print("NUMERICAL RANK GRIDS (for heatmap plots)")
    print("="*60)
    all_grid_results = {}
    for name, g_expr in frictions.items():
        print(f"\n  Computing grid for {name}...")
        q_vals, p_vals, xi_slices, grids = numerical_rank_grid(g_expr, name)
        all_grid_results[name] = (q_vals, p_vals, xi_slices, grids)

    save_results(all_grid_results)

    # Save grid data for plotting
    import numpy as np
    np.savez("/Users/wujiewang/code/det-sampler/.worktrees/hormander-ergo-017/orbits/hormander-ergo-017/rank_grids.npz",
             **{f"{name}_xi{xi_val}": grids[xi_val]
                for name, (_, _, xi_slices, grids) in all_grid_results.items()
                for xi_val in xi_slices},
             q_vals=q_vals, p_vals=p_vals)

    print("\nDone.")
