"""Rank analysis of Lie bracket distribution for thermostat vector fields.

Computes the rank of the Lie algebra generated by {X, Y} at a dense grid
of points in (q, p, xi) space, for each of the four friction functions.

Produces heatmap data showing rank as a function of (q, p) at fixed xi slices.

Key finding: ALL four frictions (NH, Log-Osc, Tanh, Arctan) achieve full
rank 3 at generic points. The Hoermander condition does NOT distinguish them.
"""

import numpy as np
import sympy as sp
from sympy import symbols, Matrix, diff, simplify, lambdify
from itertools import combinations


def lie_bracket_sym(V1, V2, state):
    """Compute Lie bracket [V1, V2] symbolically."""
    n = len(state)
    DV1 = sp.zeros(n, n)
    DV2 = sp.zeros(n, n)
    for i in range(n):
        for j in range(n):
            DV1[i, j] = diff(V1[i], state[j])
            DV2[i, j] = diff(V2[i], state[j])
    return simplify(DV2 * V1 - DV1 * V2)


def build_bracket_lambdas(g_expr):
    """Build lambdified bracket functions for fast numerical evaluation."""
    q, p, xi, Q = symbols('q p xi Q', real=True)
    state = Matrix([q, p, xi])

    X = Matrix([p, -q, 0])
    Y = Matrix([0, -g_expr * p, (p**2 - 1) / Q])

    # Compute brackets
    XY = lie_bracket_sym(X, Y, state)
    XXY = lie_bracket_sym(X, XY, state)
    YXY = lie_bracket_sym(Y, XY, state)
    XXXY = lie_bracket_sym(X, XXY, state)
    YXXY = lie_bracket_sym(Y, XXY, state)
    XYXY = lie_bracket_sym(X, YXY, state)

    all_brackets = [X, Y, XY, XXY, YXY, XXXY, YXXY, XYXY]

    # Lambdify each bracket vector
    bracket_funcs = []
    for bvec in all_brackets:
        # Returns a list of 3 floats
        f = lambdify((q, p, xi, Q), [bvec[0], bvec[1], bvec[2]], 'numpy')
        bracket_funcs.append(f)

    return bracket_funcs


def compute_rank_grid(bracket_funcs, q_range, p_range, xi_val, Q_val, tol=1e-8):
    """Compute rank of bracket distribution on a (q, p) grid at fixed xi."""
    nq = len(q_range)
    np_ = len(p_range)
    rank_grid = np.zeros((np_, nq), dtype=int)

    for i, qv in enumerate(q_range):
        for j, pv in enumerate(p_range):
            cols = []
            for bf in bracket_funcs:
                try:
                    vec = bf(float(qv), float(pv), float(xi_val), float(Q_val))
                    cols.append([float(v) for v in vec])
                except Exception:
                    cols.append([0.0, 0.0, 0.0])
            M = np.array(cols).T  # 3 x N_brackets
            rank = np.linalg.matrix_rank(M, tol=tol)
            rank_grid[j, i] = rank

    return rank_grid


def compute_rank_volume(bracket_funcs, Q_val, n_samples=10000, seed=42):
    """Monte Carlo estimate of the measure of rank-deficient set.

    Samples uniformly from a box and counts fraction with rank < 3.
    """
    rng = np.random.default_rng(seed)
    q_samples = rng.uniform(-4, 4, n_samples)
    p_samples = rng.uniform(-4, 4, n_samples)
    xi_samples = rng.uniform(-4, 4, n_samples)

    n_full = 0
    n_rank2 = 0
    n_rank1 = 0

    for k in range(n_samples):
        cols = []
        for bf in bracket_funcs:
            try:
                vec = bf(q_samples[k], p_samples[k], xi_samples[k], Q_val)
                cols.append([float(v) for v in vec])
            except Exception:
                cols.append([0.0, 0.0, 0.0])
        M = np.array(cols).T
        rank = np.linalg.matrix_rank(M, tol=1e-8)
        if rank == 3:
            n_full += 1
        elif rank == 2:
            n_rank2 += 1
        else:
            n_rank1 += 1

    return {
        'rank3_frac': n_full / n_samples,
        'rank2_frac': n_rank2 / n_samples,
        'rank1_frac': n_rank1 / n_samples,
    }


def main():
    xi_sym = symbols('xi', real=True)

    frictions = {
        'NH': xi_sym,
        'Log-Osc': 2 * xi_sym / (1 + xi_sym**2),
        'Tanh': sp.tanh(xi_sym),
        'Arctan': sp.atan(xi_sym),
    }

    n_grid = 60
    q_range = np.linspace(-3, 3, n_grid)
    p_range = np.linspace(-3, 3, n_grid)
    xi_slices = [-2.0, -0.5, 0.0, 0.5, 2.0]
    Q_val = 0.5

    all_results = {}

    for name, g_expr in frictions.items():
        print(f"\nBuilding brackets for {name}...")
        bfuncs = build_bracket_lambdas(g_expr)

        grids = {}
        for xi_val in xi_slices:
            print(f"  Computing rank grid at xi={xi_val}...")
            grid = compute_rank_grid(bfuncs, q_range, p_range, xi_val, Q_val)
            grids[xi_val] = grid
            n_full = np.sum(grid == 3)
            n_total = grid.size
            print(f"    rank=3: {n_full}/{n_total} ({100*n_full/n_total:.1f}%)")

        # Monte Carlo volume estimate
        print(f"  Monte Carlo rank analysis (10k samples)...")
        vol = compute_rank_volume(bfuncs, Q_val, n_samples=10000)
        print(f"    rank=3: {vol['rank3_frac']*100:.2f}%, "
              f"rank=2: {vol['rank2_frac']*100:.2f}%, "
              f"rank<=1: {vol['rank1_frac']*100:.2f}%")

        all_results[name] = {
            'grids': grids,
            'volume': vol,
        }

    # Save grid data
    save_dict = {'q_range': q_range, 'p_range': p_range}
    for name, res in all_results.items():
        for xi_val, grid in res['grids'].items():
            key = f"{name.replace('-','_')}_xi{xi_val:+.1f}"
            save_dict[key] = grid

    outpath = "/Users/wujiewang/code/det-sampler/.worktrees/hormander-ergo-017/orbits/hormander-ergo-017/rank_grids.npz"
    np.savez(outpath, **save_dict)
    print(f"\nSaved grid data to {outpath}")

    # Save summary
    summary_path = "/Users/wujiewang/code/det-sampler/.worktrees/hormander-ergo-017/orbits/hormander-ergo-017/rank_summary.txt"
    with open(summary_path, 'w') as f:
        f.write("# Lie Bracket Rank Analysis Summary\n")
        f.write(f"# Grid: {n_grid}x{n_grid}, Q={Q_val}, xi_slices={xi_slices}\n")
        f.write(f"# Monte Carlo: 10000 samples in [-4,4]^3, seed=42\n\n")
        for name, res in all_results.items():
            f.write(f"\n## {name}\n")
            f.write(f"  Monte Carlo: rank3={res['volume']['rank3_frac']*100:.2f}%, "
                    f"rank2={res['volume']['rank2_frac']*100:.2f}%\n")
            for xi_val, grid in res['grids'].items():
                n_full = np.sum(grid == 3)
                n_total = grid.size
                f.write(f"  xi={xi_val:+.1f}: rank3={n_full}/{n_total} "
                        f"({100*n_full/n_total:.1f}%)\n")
    print(f"Saved summary to {summary_path}")

    return all_results


if __name__ == '__main__':
    main()
